all: part1 part2
part1: day4_part1_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra day4_part1_solution.cpp -lcrypto -o part1
part2: day4_part2_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra day4_part2_solution.cpp -lcrypto -o part2

