all: part1 part2
part1: day5_part1_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra  day5_part1_solution.cpp -lcrypto -o part1
part2: day5_part2_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra day5_part2_solution.cpp -o part2

