all: part1 part2
part1: day24_part1_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra day24_part1_solution.cpp -o part1
part2: day24_part2_solution.cpp
	g++ -std=c++20 -g3 -O3 -Wall -Wextra day24_part2_solution.cpp -o part2

